name: GlowCrafts
version: '1.0.0'
main: pluginsfix.glowcrafts.GlowCrafts
api-version: '1.21'
author: pluginsfix
folia-supported: true
dependencies:
  server:
    Vault:
      load: BEFORE
      required: false
